### ISSUE TITLE
Gyro bug

### ISSUE THREAD

**Issue by Webster20002** [silver13/h8mini-testing#15]
Hello guys, I flashed an H8 mini with the silverware and it all worked fine until today, where I also flashed the software to a H8 of a friend. Now the top right motor only spins if I hold the Quad upside down. So I guess there is something wrong with the gyro. This causes an instant flip on the ground if I want to take of. The acromode works fine, but not levelmode. I also tried to calibrate the gyro but that doesnt help. I also didnt changed any setting in the config. The issue appeared after I flashed it to the H8 of a friend and on mine. Both have the same problem now.

**Comment by skohlbr** [comment]
Gyros measure angular rates and are used with acro mode, so given that acro mode works, the gyros appear to be fine. For estimating the roll and pitch in level mode, the accelerometers are used additionally however, so something could be amiss with those. Have you calibrated accelerometers with the quad resting on level ground (Pitch stick down 3 times)?

**Comment by Webster20002** [comment]
Thanks for the reply. Yes ive tried to calibrate the accelerometers but that doesnt help. The front right motor isnt spinning. The other 3 spins. If I hold the quad upside down, the back left motor doesnt spin but the other 3 do.

**Comment by silver13** [comment]
Hi, I just checked the latest code and it works fine on mine.

Did you use the same code for your friend's quad, then for yours? Perhaps some typo made it's way in the right place. I recommend you re-download the code, and try the defaults just to check that if works correctly.

Also, did you use keil? There was a linux issue, that was fixed as far as I know. I also assume you have the green board.

Thank you for posting this issue, sorry you are having problems.

**Comment by Webster20002** [comment]
Hi, thanks for your fast reply! I use keil on windows and I flashed two h8 minis with blue boards. And I also used the same code for both quads. Was that correct or is there a specific procedure if you want to flash more than one quad? I also tried to redownload your silverware again but I think I also have to redownload keil and maybe even MDK because the Problem still exists. The code worked fine until I tried to flash it on the quad of my friend. I erased his firmware but when I wanted to download the new one there came an error (cant remember which one). So I repeated everything (updating st link, etc.) and tried again and it worked. After that I also flashed it to mine quad, because I thought the code was ok, but now both have the described issue. Thanks for helping me.

**Comment by silver13** [comment]
I tested the blue board now, and that also works, there have been some updates, are you using the latest code? ( 2 weeks ago was last).

If it got flashed, it should be ok. Perhaps you changed something accidentally, I think you should try to download the latest code again, and see if that fixes it.

I don't think re-downloading keil will help, it does sound like a software issue in the quad code

**Comment by Webster20002** [comment]
I am going to try to download and flash it again with the newest software. Thanks for your help. I let you know if it worked.

**Comment by Webster20002** [comment]
So i downloaded the newest software and realised I used your other software the H8mini_blue_board. So sorry for posting this below the wrong software. I downloaded this software now but when I want to erase the chip it says: „Flash Timeout. Reset the Target and try it again." What do I have to do? If I try to download it without erasing it says the same + „Flash Download failed - Cortex-M3"

**Comment by Webster20002** [comment]
It also gives me 1 warning after building if that helps.

**Comment by silver13** [comment]
The cortex m3 is for the green board, make sure you are using the blue code for the blue board, not this one the bug is filed under.

**Comment by Webster20002** [comment]
I just downloaded the blue board version again and now I know where the issue was. I wanted to set up the trim buttons, that I can use them again so I set the level mode manual trims in degrees both to 1.0 because I thought the quad will adjust his position by clicking the button once by 1 degree. If you set it to 1.0 like I did then you get my described issue. Now I set them to 0.0 again and the quad flys again. This leads my to my next question. How to setup the trim buttons that they work like in the stock software? I still use the stock transmitter and also enabled USE_STOCK_TX but the trims doesnt work for me. Anyway thank you very much for your help and the awsome firmware!

**Comment by silver13** [comment]
the blue board does not have the trim buttons usable right now, I was planning to add them, but it seems I keep leaving it for another day.

However, setting manual trims to one should not kill the quad, I'll have to look at the code tommorow

**Comment by Webster20002** [comment]
adding the trims would be very cool. Thanks for your work.

**Comment by silver13** [comment]
I added the trims and also, manual trims should work as intended now

**Comment by Webster20002** [comment]
Thank you very much for the trims. I finally managed to tune your pid preset for the 8,5 mm frame to my setup. Now it flies awsome in levelmode and I can practise now. Greetings

**Comment by silver13** [comment]
excellent, glad it's working out
